### ISSUE TITLE
[NES.Emu] Custom palette selection seems to crash the app.

### ISSUE THREAD

**Issue by IdiotBlueMage** [Rakashazi/emu-ex-plus-alpha#248]
I keep my palette files in a separate place from my NES ROM files, so I need to go there by picking a file.  Unfortunately when I select a file using this method, the app immediately crashes out.

EDIT: Also when looking for my BIOS files in MD.emu to make sure it knows where they are, I found out that the app can't see them anymore.  It goes to where the BIOS files are located, but shows the folder as empty.

**Comment by Rakashazi** [comment]
Thanks, NES palette issue is fixed now and will go into 1.5.57.

I'm not getting the BIOS issue in MD.emu over here, did you grant that folder permission using Browse For Folder? The old direct file paths won't work anymore on Android 11+.

**Comment by IdiotBlueMage** [comment]
Thanks!

Alright, with MD.emu I could only select folder permissions through Open Content.  So I did that and in Open Content I can see the bin files.  But when I went back to the system options it still won't see the files for ke to select.

**Comment by IdiotBlueMage** [comment]
I just checked with PCE.Emu and looking for the Disksys.rom in NES and the same thing happens.  I should probably note that on NES the Palette picker uses the same file selection as opening content (Select file, select folder, etc), while when looking for the disksys.rom I just have "select file" and "unset" options.

**Comment by Rakashazi** [comment]
That's odd, I went to the BIOS menu item for each emulator, and then Select File -> Top bar -> Browse For Folder, and the files showed up. Is that how you were trying to set the BIOS?

**Comment by IdiotBlueMage** [comment]
Ah, that did it!  I'm awfully sorry, I didn't know that you could hit the top bar while setting BIOS files!  That just worked for all three emus.

Sorry about that!
